---
title: "Interactivity"
subtitle: "EMSE 4572 / 6572: Exploratory Data Analysis"
format: html
---

```{r}
#| label: setup
#| include: false

knitr::opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    fig.path = "figs/",
    fig.width = 7.252,
    fig.height = 4,
    comment = "#>",
    fig.retina = 3
)

# Use these commands to install them if you have not already
# install.packages('plotly')
# install.packages('htmlwidgets')
# install.packages('htmltools')
# install.packages('leaflet')
# install.packages('DT')
# install.packages('reactable')
# install.packages('reactablefmtr')
# install.packages('sparkline')
# install.packages('shiny')
# install.packages('shinyWidgets')
# install.packages('rsconnect')

# Should be installed from previous classes:
library(knitr)
library(tidyverse)
library(here)
library(fontawesome)
library(countdown)
library(metathis)
library(viridis)
library(cowplot)
library(rnaturalearth)
library(rnaturalearthhires)
library(rnaturalearthdata)
library(rvest)

# New
library(leaflet)
library(plotly)
library(DT)
library(reactable)
library(reactablefmtr)
library(sparkline)

# Read in data sets
gapminder <- read_csv(here::here("data", "gapminder.csv"))
internet_users <- read_csv(here::here('data', 'internet_users_country.csv'))
internet_regions <- read_csv(here('data', 'internet_users_region.csv'))
```

# 1. Interactive Charts

Here are two examples of interactive charts using `ggplotly()`

Make the static internet usage dumbbell chart:

```{r}
#| label: internet-usage-dumbbell
#| fig.height: 4
#| fig.width: 6
#| fig.align: 'center'

internet_regions_compare <- internet_regions %>%
  filter(year %in% c(2000, 2015)) %>%
  mutate(
    numUsers = numUsers / 10^6,
    year = as.factor(year))

dumbbell_chart <- internet_regions_compare %>%
  mutate(region = fct_reorder2(region, year, -numUsers)) %>%
  ggplot(aes(x = numUsers, y = region)) +
  geom_line(
    aes(group = region),
    color = 'lightblue', linewidth = 1) +
    geom_point(aes(color = year), size = 2.5) +
    scale_color_manual(values = c('lightblue', 'steelblue')) +
    scale_x_continuous(limits = c(0, 1200)) +
    theme_minimal_vgrid() +
    # Remove y axis line
    theme(axis.line.y = element_blank()) +
    labs(x = 'Millions of internet users',
         y = 'Region',
         color = 'Year',
         title = 'Number of internet users by world region',
         subtitle = "(2000 - 2015)")

dumbbell_chart
```

Make the interactive version

```{r}
ggplotly(dumbbell_chart)
```





# 2. Interactive Tables

Use `reactable()` to make the following interactive table

Read [this example](https://kcuilla.github.io/reactablefmtr/articles/embed_img.html) and use the `gapminder_flags` data frame

```{r}
# Webscrape to get the urls to images of each flag by country name
# Source: https://www.countryflags.com/

country_flags <- data.frame(
  flag = read_html('https://www.countryflags.com/') %>%     
    html_nodes('img') %>% 
    html_attr('src') 
) %>% 
  mutate(
    country = str_replace(flag, 'https://cdn.countryflags.com/thumbs/', ''),
    country = str_replace(country, '/flag-square-250.png', '')
  )

# Join on flag urls to gapminder data
gapminder_flags <- gapminder %>%
  filter(year == 2007) %>% 
  mutate(country = str_to_lower(country)) %>% 
  left_join(country_flags, by = 'country') %>% 
  select(flag, country, everything())
```

```{r}
#| label: gapminder_reactable_flags
#| echo: false

gapminder_flags %>%
  reactable(
    searchable = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    defaultPageSize = 5,
    showPageSizeOptions = TRUE,
    pageSizeOptions = c(5, 10, 15),
    columns = list(flag = colDef(cell = embed_img(
      width = "30", height = "20")))
  )
```
