---
title: "Maps"
params:
  number: 10
  purpose: 'The purpose of this assignment is to learn some techniques for creating a special type of chart: maps. We will look at different types of maps and how to work with different types of geospatial data.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

{{< include ../fragments/hw-get-organized.qmd >}}

# 2. Video

Watch [this video](https://www.youtube.com/watch?v=kIID5FDi2JQ) on map projections:

<iframe width="560" height="315" src="https://www.youtube.com/embed/kIID5FDi2JQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# 3. Readings

This week we'll learn about maps and geospatial data. Maps are a unique type of data viz, and often times they are inappropriately or inaccurately used. These readings will help you learn best practices when visualizing geospatial data:

- Wilke: [15 - Visualizing geospatial data](https://clauswilke.com/dataviz/geospatial-data.html)
- [XKCD: Map projections](https://xkcd.com/977/)
- Healy: [7 - Draw maps](http://socviz.co/maps.html#maps)
- Drawing beautiful maps: Parts [one](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html), [two](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-2.html), & [three](https://www.r-spatial.org/r/2018/10/25/ggplot2-sf-3.html)

# 4. A map worth talking about

Find a map you've seen recently, or one you just think is interesting, and put it in your `hw10.qmd` file under the "A map worth talking about" heading. Add a link to where you found it, then write a few notes answering these questions:

- What is actually being mapped - a count, a rate, a category, something else? If it's colored by a raw count, is it really just a population map?
- What projection does it look like it's using, and does that distort the areas the map is making a claim about?
- Would this be clearer as a map, or would a plain bar chart or table have told the story better?

The "Tip of the week" at the top of your `hw10.qmd` file covers how to insert an image in Quarto - captions, sizing, alt text, and how to put two maps side by side for comparison.

# 5. Reflect

{{< include ../fragments/hw-reflect.qmd >}}

# 6. Submit

{{< include ../fragments/hw-submit.qmd >}}
