---
title: "Cleaning Data"
params:
  number: 3
  purpose: 'The purpose of this assignment is learn some techniques for dealing with messy data. Most of the time, the raw data you get is in the wrong format and variables are not properly coded, so you will need to "clean" the data before starting any analysis. Other times the data will be split into two or more data sets, and you will need to "join" them together into a single data frame.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

{{< include ../fragments/hw-get-organized.qmd >}}

# 2. Read & Practice

- [Stat 545 chapter 15 on joining two tables](https://stat545.com/join-cheatsheet.html)
- [Tips for Cleaning Messy Data in R](https://rfortherestofus.com/2019/12/how-to-clean-messy-data-in-r/)
- Alison Hill had an excellent free course on DataCamp called [Working with Data in the Tidyverse](https://learn.datacamp.com/courses/working-with-data-in-the-tidyverse), but it was unfortunately archived. The content she covered though was made available as a single webpage version that is archived [here](https://web.archive.org/web/20221103133358/https://rpubs.com/cliex159/864632). The whole course is quite useful for learning some data cleaning skills. In particular, I suggest going through parts 2 ("Tame your data") and 4 ("Transform your data") to be best-prepared for dealing with messy real-world data.
- **Use AI to Practice Joining Data**: Using an agent, ask for help creating a demo to practice the concept of joining data frames in R using the tidyverse. Your agent should directly edit the ``r hw_file`` file. Once you have some examples to work with, ask the agent questions about joins to make sure you understand the concept. Are you certain the code it gave you is correct? Here is an example prompt to try (feel free to experiment with other prompts):

> `I'm practicing the concept of joining data frames in R. Provide me an example of two datasets that have a common column and then show me R code for how to join them using the tidyverse. Afterwards, show several more slightly more complicated examples where the column names don't align, etc. In each case, explain your reasoning in addition to writing the code. Directly edit the hw3.qmd file.`

# 3. Reflect

> **This week, consider writing about the messiest data you've ever had to work with.**

{{< include ../fragments/hw-reflect.qmd >}}

# 4. Submit

{{< include ../fragments/hw-submit.qmd >}}
