---
title: "Visualizing Information"
params:
  number: 5
  purpose: 'The purpose of this assignment is to learn what makes a "good" information visualization, which is _not_ entirely a subjective judgment. There are a wide variety of design principles available to help guide the creation of clear, effective information visualizations, many of which are rooted in research on human psychology.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

{{< include ../fragments/hw-get-organized.qmd >}}

# 2. Read & Practice

> "Data visualization is part art and part science. The challenge is to get the art right without getting the science wrong and vice versa."
>
> -- Claus O. Wilke in [Fundamentals of Data Visualization](https://clauswilke.com/dataviz/introduction.html)

### Readings on visualizing information

These two chapters cover a lot of excellent examples of what makes a chart "good" and "bad"---the focus of what we'll talk about in class next week:

- [Healy 1: Look at Data](http://socviz.co/lookatdata.html#lookatdata): What makes figures good and bad
- [Wilke 1: Introduction](https://clauswilke.com/dataviz/introduction.html): Definitions of "ugly", "bad", and "wrong" figures

### Video on the psychology of data viz

Watch [this 40-minute video](https://www.youtube.com/watch?v=fSgEeI2Xpdc) titled "How humans see data", by John Rauser. He discusses how we can exploit our understanding of human psychology to design effective charts (I'll cover much of the same information in the video in class next week).

<center>
<iframe width="560" height="315" src="https://www.youtube.com/embed/fSgEeI2Xpdc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</center>

# 3. Make a chart (or a bunch of charts)

Go to the [Data to Viz](https://www.data-to-viz.com/) website and find a visualization that you find interesting. Then click on "R Graph Gallery" to view an example of how to make that types of chart in R using ggplot. In a code chunk, replicate that code and see if you can get it to run on your machine.

Then make as many charts as you want. I recommend spending a little time trying to create more than one kind of chart using ggplot. For example, you could go back to the first day of class slides and try to create the [bonus charts](https://eda.seas.gwu.edu/2026-Fall/class/1-getting-started/?panelset_002=code2#145). Or you could review the [homework on data visualization](https://p4a.seas.gwu.edu/2025-Spring/hw/10-data-visualization.html) from my spring course and try to make a chart with one of the datasets from that assignment. Or go find something else, perhaps a dataset from your project! The more time you spend trying out things with ggplot, the more comfortable you will be with it. We'll be using a LOT of ggplot in the coming month, so getting comfortable with ggplot is a good idea.

# 4. Reflect

> **This week, consider writing about one of the best (or worst) data visualizations you've seen.**

{{< include ../fragments/hw-reflect.qmd >}}

# 5. Submit

{{< include ../fragments/hw-submit.qmd >}}
