---
title: "Trends"
params:
  number: 8
  purpose: 'The purpose of this assignment is to learn some of the technical details of how to create charts that highlight **trends**, which inherently involve changes in values over time.'
---

```{r child = here::here("fragments", "hw.qmd")}
```

# 1. Get Organized

Follow these instructions:

1. Download and edit [this template](`r url_template`).
2. Unzip the template folder. **Make sure you actually unzip it**! (in Windows, right-click it and use "extract all")
3. Open the .Rproj file to open RStudio.
4. Inside RStudio, open the ``r hw_file`` file, take notes, and write some example code as you go through the readings / exercises below.

# 2. Readings

Most of the readings this week have code in them that illustrate how to create each chart type, and I encourage you to try and reproduce the examples provided in R yourself.

- Wilke: [13 - Visualizing time series](https://clauswilke.com/dataviz/time-series.html)
- Wilke: [14 - Visualizing trends](https://clauswilke.com/dataviz/visualizing-trends.html)

Some examples of visualizations we'll explore in class:

- The "bar chart race": [Changes in how couples meet over time](https://flowingdata.com/2019/03/15/shifts-in-how-couples-meet-online-takes-the-top-spot/)
- The heatmap: [How common is your birthday?](https://www.vizwiz.com/2012/05/how-common-is-your-birthday-find-out.html)
- [Time-Series Heatmaps](https://towardsdatascience.com/time-series-calendar-heatmaps-9f576578fcfe)

Optional:

- [The Sankey diagrams (a.k.a. flow chart)](https://www.data-to-viz.com/graph/sankey.html)
- Video: [The fallen of WWII](http://www.fallen.io/ww2/)

# 3. Video

This video by Hans Rosling is a great summary of his larger [TED talk](https://www.ted.com/talks/hans_rosling_the_best_stats_you_ve_ever_seen) on the "gapminder" project he started showing life expectancy and GDP over time. This is an excellent example of using an _animated_ chart to tell a much richer story than a static chart.

<iframe width="560" height="315" src="https://www.youtube.com/embed/jbkSRLYSojo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

# 4. Reflect

> **This week, consider writing about an interesting data visualization about trends you've seen.**

{{< include ../fragments/hw-reflect.qmd >}}

# 5. Submit

{{< include ../fragments/hw-submit.qmd >}}
